Release candidate
KomodoPlatform/sia-rust pull request #3
Opened 2024-10-02 16:01 UTC by Alrighttt

To do:
- implement methods in V2TransactionBuilder for atomic swap signing
- Generic error handling in the dispatcher. Should be generalized providing a standard error message format. 
- Implement the remaining file contract related types for V2Transaction
- Move the [example client](https://github.com/KomodoPlatform/sia-rust/blob/refactor_hash_types/src/http/client/example.rs) to a rust doc example ref: https://doc.rust-lang.org/cargo/reference/cargo-targets.html#examples

2024-10-02 19:06 UTC, borngraced commented
working on task 3 && 4

2024-10-05 13:47 UTC, laruh commented
could you add `.idea` to gitignore?

2024-10-05 15:00 UTC, laruh requested changes
Thanks for the PR! there are the first notes

2024-10-05 15:00 UTC, laruh commented on src/types/hash.rs
> +    fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
You can avoid using `::core::` here, similar to the other implementations

2024-10-05 15:00 UTC, laruh commented on src/transport/client/example.rs
You can leave notes at the top of the file as file-level doc comment
```
//! THIS FILE MUST NOT INCLUDED IN WORKSPACE
//! **Some Broken Code to Ensure the Build Fails if this File is Included in the Workspace**
```

2024-10-05 15:00 UTC, laruh commented on src/types/specifier.rs
Suggest to improve `define_byte_array_const` macro like this:
```rust
use static_assertions::const_assert;

macro_rules! define_byte_array_const {
    ($name:ident, $size:expr, $value:expr) => {
        pub const $name: [u8; $size] = {
            // Array size must be at least as large as the value length
            const_assert!($size >= $value.len());

            let mut arr = [0u8; $size];
            let bytes = $value.as_bytes();
            let mut i = 0;
            while i < bytes.len() && i < $size {
                arr[i] = bytes[i];
                i += 1;
            }
            arr
        };
    };
}
```
const_assert! ensures that $size is greater than or equal to $value.len() at compile time. This means if there's a violation, the compile will fail, preventing unsafe operations.

Cargo lock already contains `static_assertions`, so its ok to add `static_assertions` as a dep. It will be just added in sia-rust `[[package]]`
https://github.com/KomodoPlatform/sia-rust/blob/9b79ae3605d3deaa1a04076ae86530b8f84065c4/Cargo.lock#L1309-L1313

2024-10-24 12:19 UTC, mariocynicys commented
Grabbed task 5: Wrap all relevant unit tests with cross_target_tests [example](https://github.com/KomodoPlatform/sia-rust/blob/9b79ae3605d3deaa1a04076ae86530b8f84065c4/src/tests/transaction.rs#L11)

2024-10-24 15:05 UTC, mariocynicys commented
Grabbed task 3: Generic error handling in the dispatcher. Current error handling still has remnants of now refactored dispatcher. [ref](https://github.com/KomodoPlatform/sia-rust/blob/2b8676144873bb051446f7d14f2ccd02f6755feb/src/http/client.rs#L58C1-L78C2)

2024-10-25 09:20 UTC, mariocynicys commented
Grabbed task 6: Migrate [docker test framework](https://github.com/KomodoPlatform/komodo-defi-framework/blob/b2bc13a3b53c94c03b1081ed2621dc4d846465e7/mm2src/mm2_main/tests/docker_tests/sia_docker_tests.rs) from Komodo DeFi Framework into Sia Rust. There are tests throughout the codebase that rely on a hardcoded URL to a walletd index node. Remove these in favor of mocked API or walletd docker containers.

2025-02-21 15:08 UTC, merged